version: "3.5"
services:
    tlip.node:
        image: iotazebra/tlip-node:latest
        env_file:
            - .env
        ports:
            - 4000:4000
        volumes:
            - ./.dev-config/config.json:/usr/app/dist/apps/api/rest-server/assets/config.json
        restart: always

    uni-resolver-web:
        image: universalresolver/uni-resolver-web:latest
        ports:
            - 8080
        environment: 
            _JAVA_OPTIONS: -Dlogging.level.uniresolver.client=TRACE

    driver-did-iota:
        image: iotaledger/uni-resolver-driver-iota:latest
        environment:
            IOTA_CUSTOM_NETWORK_NAME: ebsi
            IOTA_CUSTOM_NODE_ENDPOINT: "https://api.stable.iota-ec.net"
            IOTA_CUSTOM_NODE_AUTH_TOKEN: "eyJh"
            
#    driver-did-iota:
#        image: iotaledger/uni-resolver-driver-iota:v0.2.0-alpha
#        environment:
#            NETWORK: testnet

    my-sql:
        image: mysql:8.4.4
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=my-secret-pw
        volumes: 
            - ./dev-storage-mysql:/var/lib/mysql

