version: "3.5"
services:
    federation-service:
        image: iotazebra/fed-catalogue-service:latest
        env_file:
            - ./.env.docker
        ports:
            - 3020:3020
        volumes:
            - ./.local-data-docker:/usr/src/app/.local-data
        restart: always
